# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Authen-PluggableCaptcha
version:      0.01
version_from: PluggableCaptcha.pm
installdirs:  site
requires:
    Time::HiRes:                    1.87
    Digest::MD5:                    2.35
    Number::Spell:                  0.04
    Data::Dumper:                   2.121

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
